default_env: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mailman
  pool: 5
  username: root
  password: root
  host: db

development:
  <<: *default
  database: mailman

test:
  <<: *default
  database: mailman_test
