broker:
  main_topic: 'mailer'
  backup_topic: 'backup-mailer'
  status_topic: 'status'
  partition: 'mail'
web:
  success: 'http://localhost/mail/:id/sent'
  failure: 'http://localhost/mail/:id/failed'

